#!/bin/bash

isRoot=0
HERE=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

[ "$EUID" -eq 0 ] && isRoot=1

throw() {
	echo "$@" >&2
	exit 1
}

if [ 1 -eq "$isRoot" ]
then
		# root install path
		echo "Installing as root."
		dest="/usr/local/bin"
		comp="/etc/bash_completion.d"
		cfg="/etc/hubget"
		cfgFile="$cfg/hubget.cfg"
else
		echo "Installing as regular user. bash_completion not included (requires root)."
		dest="$HOME/bin"
		cfg="$HOME"
		cfgFile="$HOME/.hubget.cfg"
fi

[ -d "$dest" ] || throw "Paranoid bailout - $dest not found"
# todo, offer alternate locations?

destFile="$dest/hub-get"
[ -f "$destFile" ] && throw "Paranoid bailout - $destFile already exists"
# user may have made changes

src="$HERE/hub-get.sh"
ln -s "$src" "$destFile" || throw "Error creating symlink as $destFile"
echo "Symlinked $src to $destFile"

mkdir -p "$cfg"
[ -f "$cfgFile" ] && throw "Paranoid bailout - $cfgFile already exists"
# user may have made changes

src="$HERE/default.cfg"
cp "$src" "$cfgFile" || throw "Error copying default cfg as $cfgFile"
echo "copied $src to $cfgFile"

if [ "$isRoot" -eq 1 ]
then
		[ -d "$comp" ] || throw "Could not add completion - $comp not found"
		compFile="$comp/hubget"
		[ -f "$compFile" ] && throw "Paranoid bailout - $compFile already exists"
		src="$HERE/completion.sh"
		cp "$src" "$compFile" || throw "Error copying $src to $compFile"
		echo "installed $compFile"
		. $compFile
else
		$destFile configure repo.dir "$HOME/github"
fi

echo -e "\nInstall complete!"
$destFile -h
